services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    runtime: nvidia  # This is only for Docker with nvidia-container-toolkit
    ports:
      - "8096:8096"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /media/mark/12TBDataDrive/Jellyfin/Shows/:/media/shows:ro
      - /media/mark/12TBDataDrive/Jellyfin/Movies:/media/movies:ro
      - /media/mark/12TBDataDrive/Jellyfin/4k Movies:/media/4k-movies:ro
      - /media/mark/12TBDataDrive/Jellyfin/4k TV:/media/4k-shows:ro
      - /media/mark/MediaLibrary/JellyFin/Movies:/media/movies2:ro
      - /media/mark/MediaLibrary/JellyFin/Shows:/media/shows2:ro
      - /media/mark/MainStorage/JellyFin/Books/Audiobooks/:/media/books:ro
      - /media/mark/MainStorage/JellyFin/Movies:/media/movies3:ro
      - /media/mark/MainStorage/JellyFin/Shows:/media/shows3:ro
    environment:
      - JELLYFIN_PublishedServerUrl=https://stream.marksteininger.com
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    restart: unless-stopped
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true
    name: caddy-network
