services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"  # You can remove this if you only want Caddy access
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /media/mark/12TBDataDrive/Jellyfin/Shows/:/media/shows:ro
      - /media/mark/12TBDataDrive/Jellyfin/Movies:/media/movies:ro
      - /media/mark/12TBDataDrive/Jellyfin/4k Movies:/media/4k-movies:ro
      - /media/mark/12TBDataDrive/Jellyfin/4k TV:/media/4k-shows:ro
      - /media/mark/Media Library/JellyFin/Movies:/media/movies2:ro
      - /media/mark/Media Library/JellyFin/Shows:/media/shows2:ro
      - /media/mark/New Volume/JellyFin/Books:/media/books:ro
      - /media/mark/New Volume/JellyFin/Movies:/media/movies3:ro
      - /media/mark/New Volume/JellyFin/Shows:/media/shows3:ro
    environment:
      - UDOCKER_OPTS=--device /dev/dri:/dev/dri
      - JELLYFIN_PublishedServerUrl=https://stream.marksteininger.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true
    name: caddy-network