services:
  minecraft_server:
    restart: unless-stopped
    container_name: minecraft-tekkit
    image: itzg/minecraft-server:java17-jdk
    volumes:
      - ./data:/data
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      DEBUG: "false"
      VERSION: "1.19.2"
      FORGEVERSION: "43.5.0"
      MEMORY: "8G"
      OPS: "Wuggles1"
      ALLOW_FLIGHT: "true"
      MOTD: "Greetings Friends and Welcome to Wuggles Castle"
    tty: true
    stdin_open: true